### ISSUE TITLE
fail to run model when load low bits instead of load original for qwen

### ISSUE THREAD

**Issue by aoke79** [intel-analytics/BigDL#10327]
the error message is like below:
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, xpu:0 and cpu!
Thanks a lot,

**Comment by Oscilloscope98** [comment]
Hi @aoke79 ,

In your code, when using ·load_low_bit·, is ·cpu_embedding· set to True? If so, this may due to a bug with `cpu_embedding`. We have fixed it for `bigdl-llm >= 2.5.0b20240123`. Would you mind letting us know your `bigdl-llm` version? If `bigdl-llm` is below `2.5.0b20240123`, you could update to latest `bigdl-llm` and have a try again :)

Please let us know for any further updates.
