### ISSUE TITLE
bigdl, bigdl-SPARK_2.0, bigdl-SPARK_2.1 are out of date on sonatype.

### ISSUE THREAD

**Issue by i8run** [intel-analytics/BigDL#1221]
The newest jars list:

bigdl: 20170704
bigdl-SPARK_2.0: 20170709
bigdl-SPARK_2.1: 20170709

**Comment by yiheng** [comment]
It's gone. Check the jenkins server history. Looks like from 0709 to 0718 the nightly build on jenkins cluster keep failing. The root cause is a new server is misconfigured. This has been solved.

We won't update bigdl artifact.

Currently, these four artifacts are using
bigdl-SPARK_1.5
bigdl-SPARK_1.6
bigdl-SPARK_2.0
bigdl-SPARK_2.1
