### ISSUE TITLE
Need a remove/drop API to remove last module layer to support fine tune

### ISSUE THREAD

**Issue by jenniew** [intel-analytics/BigDL#1494]
After load model, we need to modify last layers of pre-trained model to fine tune with different dataset. Now we already have API to add module,  we need remove/drop module API to do that modification.  Another use case is that we need to remove last layers( i.e. Fully Connected layer, etc.) to only extract features without doing classification.

**Comment by yiheng** [comment]
This request is ambiguous. What is the last module in a graph?

**Comment by jenniew** [comment]
The top layer

**Comment by jenniew** [comment]
Say, in topological sorting of directed graph, the last one.  Or we have a way to find a module with name, if it is possible to remove that module.

**Comment by yiheng** [comment]
@jenniew @jason-dai @hhbyyh 

I think one solution to the problem is you can get the graph of the Graph model, modify the graph and create a new Graph model on it. We can add a getNodeByName method to Graph, then for your use case, we can

1. remove the last several layers, so now we get output from e.g. conv10
```scala
val output = graph.getNodeByName("conv10")
val input = graph.getNodeByName("input")
val newModel = Graph(input, output)
```

2. replace last layer 'fc10' with different fc layer, layer 'relu' point to 'fc10'
```scala
val node = graph.getNodeByName("relu")
val newOutput = Linear(...).inputs(node)
val input = graph.getNodeByName("input")
val newModel = Graph(intput newOutput)
```
