### ISSUE TITLE
Add better documents for Sum, Mean, JoinTable, Bottle and Padding

### ISSUE THREAD

**Issue by jason-dai** [intel-analytics/BigDL#394]
We need to add more detailed Scala doc and comments for these modules to make it clear what exactly the "dimension" and "nInputDims"(or "nInputDim") parameters mean; shall we make "nInputDim" a mandatory  parameter for these modules?

**Comment by psyyz10** [comment]
I have made the documentation including more details. However, I am not sure using which strategy to handle the case. There are two selectable choices:
1. make "nInputDim" a mandatory parameter for these modules
    Drawback: the user have to calculate matrix dimensions and understand `nInputDim`
2. add 'val batch: Boolean = false' to the AbstractModule. If the user want to use batch, they can set the batch mode to true. In this case `nInputDim` may be need to be removed, because the modules decides whether to do batch operations by the `batch` parameters. If `batch` and `nInputDim` exists simultaneously, the module may not know decide by which signal. In this case, we can set `batch` to true in the Optimizer class.
   DrawBack: the user have to set batch mode to true, if they want to use batch. they may not know or forget to do these.

Do you have any advice @jason-dai @yiheng ?

**Comment by jason-dai** [comment]
I think we can keep the current behavior for now; just add more documents. 

There are a few options, and we can make a decision later.
1. Make "nInputDim" mandatory 
2. Add a flag for batch mode
3. Automatically determine the value of "nInputDim" by analyzing the graph

**Comment by jason-dai** [comment]
Fixed via #408
