### ISSUE TITLE
Removing RDD's at the end is tooo long. Kindly advise

### ISSUE THREAD

**Issue by jaymahesh** [intel-analytics/BigDL#538]
I ran my Spark standalone mode 1 Master + 2 Worker nodes -96GB each (deploy client mode) and ran the bigdl script (given at the bottom) and everything is fine except that **after writing** the model file into the directory my program is delayed for too long  with removing RDD's

17/03/03 14:52:39 INFO MemoryStore: Block taskresult_533 stored as bytes in memory (estimated size 57.5 MB, free 46.8 GB)
17/03/03 14:52:39 INFO Executor: Finished task 0.0 in stage 812.0 (TID 533). 60263236 bytes result sent via BlockManager)
17/03/03 14:55:44 INFO BlockManager: Removing RDD 8
17/03/03 14:55:44 INFO BlockManager: Removing RDD 9
17/03/03 14:55:44 INFO BlockManager: Removing RDD 15
17/03/03 14:55:44 INFO BlockManager: Removing RDD 16
17/03/03 14:55:44 INFO BlockManager: Removing RDD 17
17/03/03 14:55:45 INFO BlockManager: Removing RDD 18
17/03/03 14:55:45 INFO BlockManager: Removing RDD 19
17/03/03 14:55:45 INFO BlockManager: Removing RDD 20
17/03/03 15:14:17 INFO BlockManager: Removing RDD 7
17/03/03 15:14:17 INFO BlockManager: Removing RDD 6
17/03/03 15:14:17 INFO BlockManager: Removing RDD 419
17/03/03 15:14:18 INFO BlockManager: Removing RDD 5
****
bigdl.sh below    
spark-submit --class com.intel.analytics.bigdl.models.vgg.Train --driver-memory 32g \
--master spark://192.168.1.202:7077 \
  --executor-memory 96G \
  --total-executor-cores 50 \
  /root/BigDL/dist/lib/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar \
 --maxEpoch 1 \
--core 64 \
--node 1 \
--env spark \
-f /root/cifar-10-batches-bin/ \
-b 256 \
--checkpoint ~/model

**Comment by jaymahesh** [comment]
The Linux command prompt shows this at the end

2017-03-03 14:51:59 INFO  DistriOptimizer$:286 - [Epoch 1 49920/50000][Iteration 196][Wall Clock 437.720223938s] Epoch finished. Wall clock time is 440426.314292ms
2017-03-03 14:51:59 INFO  DistriOptimizer$:431 - [Wall Clock 440.426314292s] Validate model...
can't find locality partition for partition 0 Partition locations are (ArrayBuffer(192.168.1.182)) Candidate partition locations are
(0,ArrayBuffer(192.168.1.173)).
2017-03-03 14:52:13 INFO  DistriOptimizer$:471 - top1 accuracy is Accuracy(correct: 1001, count: 10000, accuracy: 0.1001)
[Wall Clock 440.426314292s] Save model to /root/model

**Comment by jaymahesh** [comment]
Hi @jason-dai @yiheng 
Request your feedback on my above issue when you get a chance, thanks

**Comment by yiheng** [comment]
Hi

First questions like this should go to the email group bigdl-user-group@googlegroups.com instead of open issue.

I can see some inconsist in your command
bigdl.sh below
spark-submit --class com.intel.analytics.bigdl.models.vgg.Train --driver-memory 32g
--master spark://192.168.1.202:7077
--executor-memory 96G
**--total-executor-cores 50**
/root/BigDL/dist/lib/bigdl-0.1.0-SNAPSHOT-jar-with-dependencies.jar
--maxEpoch 1
**--core 64
--node 1**
--env spark
-f /root/cifar-10-batches-bin/
-b 256
--checkpoint ~/model

The total core is 50 but the node core is 64. Also you mention you have two workers but node number is 1.

Say if you have two workers, each worker has 32 core, the options should be like
--total-executor-cores 64
--executor-cores 32
...
--node 2
--core 32

**Comment by jason-dai** [comment]
Closing this issue; if there are further questions, please send them to BigDL user group (https://groups.google.com/forum/#!forum/bigdl-user-group).
