### ISSUE TITLE
NoSuchMethodError on SpatialConvolution

### ISSUE THREAD

**Issue by LeoIV** [intel-analytics/BigDL#880]
I am trying to implement a text classifier as explained [here](https://github.com/intel-analytics/BigDL/blob/master/spark/dl/src/main/scala/com/intel/analytics/bigdl/example/utils/TextClassifier.scala). The method of interest here is buildModel. 

I am writing and compiling my code on windows with the following build.sbt configuration:

```
name := "xxx"

version := "1.0"

scalaVersion := "2.11.8"

assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs@_*) => MergeStrategy.discard
  case x => MergeStrategy.first
}

test in assembly := {}

libraryDependencies += "org.apache.spark" % "spark-core_2.10" % "2.0.2" % "provided"
libraryDependencies += "org.apache.spark" % "spark-mllib_2.10" % "2.0.2" % "provided"
libraryDependencies += "org.ejml" % "core" % "0.30"
libraryDependencies += "org.ejml" % "simple" % "0.30"
libraryDependencies += "org.apache.opennlp" % "opennlp-tools" % "1.7.2"
libraryDependencies += "com.intel.analytics.bigdl" % "bigdl-SPARK_2.0" % "0.1.0" % "provided"
```

Then, i upload the fat jar to a linux system with this configuration: 
```
spark-shell --jars xxx-assembly-1.0.jar,BigDL/dist/lib/bigdl-0.2.0-SNAPSHOT-jar-with-dependencies.jar --properties-file BigDL/dist/conf/spark-bigdl.conf --driver-memory 20G --executor-memory 20G --num-executors 16


Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.0.2
      /_/

Using Scala version 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_111)

```

So the spark version are equal as well as the scala versions. Nonetheless, I get an error 
`java.lang.NoSuchMethodError: com.intel.analytics.bigdl.nn.SpatialConvolution$.apply$mFc$sp(IIIIIIIIIZLcom/intel/analytics/bigdl/nn/InitializationMethod;Lscala/reflect/ClassTag;Lcom/intel/analytics/bigdl/tensor/TensorNumericMath$TensorNumeric;)Lcom/intel/analytics/bigdl/nn/SpatialConvolution;
  at Test$.buildModel(Test.scala:143)
  at Test$.fct(Test.scala:125)
`

The method looks as follows:
```
def buildModel(classNum: Int, desiredVectorLength: Int): Sequential[Float] = {
    val model = Sequential[Float]()

    model.add(Reshape(Array(desiredVectorLength, 1, desiredVectorLength)))

    model.add(SpatialConvolution(desiredVectorLength, 128, 5, 1))
    model.add(ReLU())

    model.add(SpatialMaxPooling(5, 1, 5, 1))

    model.add(SpatialConvolution(128, 128, 5, 1))
    model.add(ReLU())

    model.add(SpatialMaxPooling(5, 1, 5, 1))

    model.add(SpatialConvolution(128, 128, 5, 1))
    model.add(ReLU())

    model.add(SpatialMaxPooling(35, 1, 35, 1))

    model.add(Reshape(Array(128)))
    model.add(Linear(128, 100))
    model.add(Linear(100, classNum))
    model.add(LogSoftMax())
    model
  }
```

What is the problem here?

**Comment by dding3** [comment]
I think the exception is caused by lib running version mismatch with compile version. There are several things needed to be updated:
1. build.sbt use bigdl_spark2.0-0.1 while bigdl-0.2 jar is used when running. Please use bigdl-SPARK_2.0-0.1.0.jar when launch spark shell. 
2. build.sbt use spark-core_2.10/spark-mllib_2.10, please update them to 2.11 as your scala version is 2.11 and spark_2.0 also use scala 2.11

I made above changes and successfully run the code in my env.

**Comment by LeoIV** [comment]
Mabye I misunderstand something but the BigDL Version when using the current version in the Github repo is 0.2.0-SNAPSHOT. There is now way of using 0.1.0-SNAPSHOT but switching to an older version of the repository. Using the description in the Building Guide, it is not possible to get BigDL running!?

**Comment by jason-dai** [comment]
@LeoIV Thanks for the feedbacks. I think the comment above says that the BigDL jar used in the command should match that of the sbt config. In the sbt config, 0.1.0 is used (`libraryDependencies += "com.intel.analytics.bigdl" % "bigdl-SPARK_2.0" % "0.1.0" % "provided"`), while in the coomand line, 0.2.0 snapshot is used (`spark-shell --jars xxx-assembly-1.0.jar,BigDL/dist/lib/bigdl-0.2.0-SNAPSHOT-jar-with-dependencies.jar`).

To use 0.1.0, you may download the release from https://github.com/intel-analytics/BigDL/wiki/Downloads; to use 0.2.0 snapshot, you may change the sbt config to something like  `libraryDependencies += "com.intel.analytics.bigdl" % "bigdl-SPARK_2.0" % "0.2.0-SNAPSHOT"`. (Please use spark-core_2.11/spark-mllib_2.11 as mentioned above, because Scala 2.11 is used to build BigDL for Spark 2.x).

We'll update the build page to make it clearer.

**Comment by LeoIV** [comment]
Yes but the Maven Repository contains no according JAR: https://mvnrepository.com/artifact/com.intel.analytics.bigdl/bigdl-SPARK_2.0
