### ISSUE TITLE
llama2 example response cut in the middle

### ISSUE THREAD

**Issue by nedo99** [intel-analytics/BigDL#8811]
Hi,

I was testing llama2 [example](https://github.com/intel-analytics/BigDL/tree/main/python/llm/example/transformers/transformers_int4/llama2), but the response is cut as you can see below:
```
-------------------- Output --------------------
### HUMAN:
what is AI?

### RESPONSE:

AI is a term used to describe the ability of machines to perform tasks that typically require human intelligence, such as learning, problem-solving, decision-making, and perception. AI systems use
```
It is the same for any other question or input. I also tried to change `n-predict` parameter for `max_new_tokens`, but whatever value I take the reply is cut. If I take 128 for example, the response is longer but cut.

Is there a way to optimize this?

Regards,
Nedim

**Comment by jason-dai** [comment]
Maybe you can try setting n-predict to an even larger value (e.g., 512)?

**Comment by yangw1234** [comment]
> > Maybe you can try setting n-predict to an even larger value (e.g., 512)?
> 
> That is the point, whatever the value you set it is still cut. I tried 512 and you get really long text, which is again cut just at a later point :)

I guess this is the expected behavior. The model is not done generating (meaning it has not generated a special EOS token) but the output token length is reached the `max_new_tokens` specified in the `generate` call, so the generation process stops.

To check it, you can add `print(len(output[0]))` and `print(len(input_ids))`in https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/transformers/transformers_int4/llama2/generate.py#L66 to see if the difference between the input and output token number is `max_new_tokens`.

You can also try a difference prompt that encourages shorter answer to see if it finished within `max_new_tokens`. (e.g. "What is capital of the United States?")

**Comment by nedo99** [comment]
That number varies. For instance `print(len(output[0]))` gives 55 and my input as `max_new_tokens` was 32. If I then set `max_new_tokens` to 58 for example,  `print(len(output[0]))` gives 79 and so on.

Is there a way to indicate to model to stop at the end of the sentence at least? I know in the langchain native int4 examples there is a `stop` parameter so you can pass something like: `stop="\n\n"`.

**Comment by yangw1234** [comment]
> That number varies. For instance `print(len(output[0]))` gives 55 and my input as `max_new_tokens` was 32. If I then set `max_new_tokens` to 58 for example, `print(len(output[0]))` gives 79 and so on.
> 
> Is there a way to indicate to model to stop at the end of the sentence at least? I know in the langchain native int4 examples there is a `stop` parameter so you can pass something like: `stop="\n\n"`.

The `model.generate` here follows the exact same API as the `generate` in huggingface transformers. See [generate](https://huggingface.co/docs/transformers/v4.32.1/en/main_classes/text_generation#transformers.GenerationMixin.generate). 

While there is no `stop` parameter in the `generate` API, people often implement their own `stopping_criteria` to insert customized stopping logic. See example [here](https://discuss.huggingface.co/t/implimentation-of-stopping-criteria-list/20040).

**Comment by nedo99** [comment]
Got it then! Thanks for the support!
