### ISSUE TITLE
Use reflection to interact with BlockManger

### ISSUE THREAD

**Issue by yiheng** [intel-analytics/BigDL#900]
BlockManger putBytes API looks like not so stable. Directly invoke it will result in multiple compiled versions for different spark platforms. Use reflection can reduce the compiled version number.

**Comment by srowen** [comment]
(BlockManager isn't an API by the way - that's the problem.)
I think this might even be higher priority, as the current builds won't likely work with Spark 2.2 which will be out soon, and 0.2.0 will want to support that.

**Comment by srowen** [comment]
I looked at this in depth today, and my first conclusion is that it would be quite hard to abstract over Spark 1.x vs 2.x given the use of private APIs. They have changed a lot and so it's probably going to be necessary to keep the two `1.5-plus` and `2.0` modules.

However, I don't see any variation in the versions of Spark 2.x _except_ for the `putBytes` method. It changed, then changed back between 2.1.0 - 2.1.1 - 2.2.0. So this one we really do need to use reflection to support, and I think that's easy.

This would let us get rid of all of the profiles except `spark_2.0`, because all 1.x versions should (?) be compatible with the base build, and all 2.x versions should then be compatible with the 2.0 build. I will try it now.
