### ISSUE TITLE
Fine-tune LLM

### ISSUE THREAD

**Issue by ernleite** [intel-analytics/BigDL#9077]
Hi team, 
I am searching a way to fine tune LLM using BigDL.
I have some good performances using llm-cli without GPU with LLama2-13B _HF models
But it would be great to fine-tune these models without the need of GPU
HF offers autotrain on prem but needs a minimum GPU 16 GB
if think being able to fine-tune a pretrained model with BigDL could be great also
Thanks

**Comment by jason-dai** [comment]
We do have experimental bf16 lora on CPU support (https://github.com/intel-analytics/BigDL/tree/main/docker/llm/finetune/lora), and qlora on Intel GPU support (https://github.com/intel-analytics/BigDL/pull/9018), which we may be able to support for CPU later.

What is the performance target you have in mind (token#, wall-clock time, CPU resources, etc.)?

**Comment by ernleite** [comment]
sounds great thanks. I have a cluster of 3 DELL R730 with 96 GB each. I will install soon one Nvidia M40 24 GB on each of them.
What is actually the minimum K8S cluster size to run that experiment? 
Thanks !

**Comment by Uxito-Ada** [comment]
Hi @ernleite ,

For k8s, we now present a [pure-CPU solution](https://github.com/intel-analytics/BigDL/tree/main/docker/llm/finetune/lora/cpu#run-bf16-optimized-lora-finetuning-on-kubernetes-with-oneccl). It does not require any GPU, and can scale to cluster with existing CPU resources. We have successfully fine-tuned Llama, Llama2 etc. LLMs with BF16, LoRA, and MPI accelerations, whose performance is comparable to GPU.

As for cluster size, there is no min limitation requirement, while stronger resources provides better performance. Our validation is on a 2-node ICX/SPR(Intel server) cluster with 96 cores respectively. MicroK8S is also viable.

For GPU, only Intel GPU is supported rather than Nvidia, which you can find in the PR Jason mentioned above.

**Comment by ernleite** [comment]
thanks a lot for your feedback!
