### ISSUE TITLE
Some Chinese character with chatglm-6b model using native_int4

### ISSUE THREAD

**Issue by WeiguangHan** [intel-analytics/BigDL#9132]
When I did benchmark tests for bigdl-llm on my local machine, I found that some Chinese characters will appear in the output. The model and api interface I used is `chatglm-6b` and `native_int4`.

![image](https://github.com/intel-analytics/BigDL/assets/109776541/6697925f-c17d-45d7-a650-ae074310d97a)

### **Env**
bigdl-core-xe-2.4.0b20231009 
bigdl-llm-2.4.0b20231009 
intel-extension-for-pytorch-2.0.110+xpu 
torch-2.0.1a0+cxx11.abi 
torchvision-0.15.2a0+cxx11.abi

**Comment by hkvision** [comment]
@MeouSker77 Take a look?

**Comment by MeouSker77** [comment]
I can reproduce this, it seems chatglm-6b will generate random output with a long English input. But it seems not a bug of BigDL-LLM, I tried original fp32 chatglm-6b with same input, it also generates wrong output. So I think this is a bug of the model itself.

I also tried chatglm2-6b, it can work correctly with same input, you can use it instead of chatglm-6b.

**Comment by WeiguangHan** [comment]
ok. I got it. Thanks a lot!
