### ISSUE TITLE
Run native INT4 model ChatGLM2-6B on SPR windows with AMX?

### ISSUE THREAD

**Issue by biyuehuang** [intel-analytics/BigDL#9240]
Hi, I know the way to run native INT4 on first socket of SPR Ubuntu with AMX. But the same way can't run on windows SPR?
If we don't use "pip install bigdl-nano and numactl -C 0-47 -m 0" on windows SPR, the performance is so wrong.

```
sudo apt install numactl
conda create -n llm python=3.9
conda activate llm
pip install bigdl-llm[all]
pip install bigdl-nano
source bigdl-nano-init -c
export OMP_NUM_THREADS=48
$ numactl -C 0-47 -m 0 llm-cli -t 48 -x chatglm -m "./checkpoint/bigdl_llm_chatglm_q4_0.bin" -p "Once upon
a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new
people, and have fun" --no-mmap -v -n 32
```

**Comment by kevin-t-tang** [comment]
在Windows验证性能只有不到1/4，问题是 bigdl 是否依赖 py-cpuinfo ?
目前调查来看，Windows上面的 py-cpuinfo 没有检查 amx 指令集

**Comment by biyuehuang** [comment]
Must use all physics core on first socket.
Run native INT4 model ChatGLM2-6B on SPR windows without AMX

```
conda create -n llm python=3.9
conda activate llm
pip install bigdl-llm[all]
pip install bigdl-nano

set OMP_NUM_THREADS=48
$ llm-cli -t 48 -x chatglm -m "./checkpoint/bigdl_llm_chatglm_q4_0.bin" -p "Once upon
a time, there existed a little girl who liked to have adventures. She wanted to go to places and meet new
people, and have fun" --no-mmap -v -n 32
```

**Comment by MeouSker77** [comment]
BigDL-LLM doesn't use AMX on Windows. But AMX only accelerates the first token.

The rest token latency depends on memory access, including memory bandwidth and whether accessing memory across NUMA nodes. `numactl -C 0-47 -m 0` can requires the program only use the first NUMA node, so that it won't access the memory of another node. On Windows, `start /node 0 <command>` under cmd can achieve the same effect, i.e. requires the `<command>` only use the first NUMA node. When running it on a machine which only has one socket, I think just `llm-cli -t 48 xxxx` is enough.

**Comment by biyuehuang** [comment]
Thank, actually check AMX don't effect after latency.
