### ISSUE TITLE
Best Known Spark Cluster  Configuration In Standalone Mode For BigDL

### ISSUE THREAD

**Issue by nsakar** [intel-analytics/BigDL#951]
I have implemented a zeppelin notebook to train and test the VGG Model on CIFAR 10.
My Spark standalone cluster has 1 master node that also doubles up as a worker node [ 187 GB RAM, 56 cores] and 4 worker nodes [ each with 16 GB and 48 GB RAM]

The zeppelin web server from where I launch the notebooks [ 16 cores , 48 GB RAM] 

After playing around with how to get optimum number of nodes and executors per core, I find the following results:

Worker node : 5, Total Cores : 64, Cores/executor: 4, Executor memory: 20 g, Training result after 25 epochs: 78 % Top1Accuracy, Training result after 50 epochs: 85 % , Batch Size : 640, Training time 4 hours for 25 epochs , 8 hours for 50.

Worker node : 5, Total Cores : 68, Cores/executor: 4, Executor memory: 20 g, Training result after 25 epochs: 78 % Top1Accuracy, Training result after 50 epochs: 85 % , Batch Size : 680, Training time 4 hours for 25 epochs , 8 hours for 50.

Worker node : 5, Total Cores : 48 , Cores/executor: 4, Executor memory: 20 g, Training result after 25 epochs: 78 % Top1Accuracy, Training result after 50 epochs: 85 % , Batch Size : 600, Training time 4 hours for 25 epochs , 8 hours for 50.

Worker node : 5, Total Cores : 90 , Cores/executor: 10, Executor memory: 20 g, Training result after 25 epochs: 12 % Top1Accuracy, Batch Size : 900, Training time 4 hours for 25 epochs

I have the following questions:

Does BigDL expect 1 executor node per worker node?
Does BigDL clone model for each executor even if they are multiple executors on same worker node?
Does Big dl partition input RDD by number of executors even if they are on same worker node? . Example if there are 12 executors distributed in 5 worker nodes, will there be 12 partitions that each executor works on?
Do all cores of an executor work on the same data set partition and aggregate trained model results before broadcasting to BlockManager?
Where does the DistributedOptimizer code run? In the spark-submit job of the client in deployMode = client?
While doing these experiments I have encountered following issues:
--netty io issues between executors and driver
--OOM issues
--job failure when only 1 task fails [ no retry on another executor]

Can you provide a best known configuration of spark standalone cluster for bigDL?

**Comment by yiheng** [comment]
Hi @nsakar

Here are my answers to your question:
For **inference** work, BigDL just works like normal Spark application. It's a full-batch job. There's no special requirement for the partition number/executor number/worker number.

For **training** work, BigDL will repartition your train data RDD to executor number partitions. So

> Does BigDL expect 1 executor node per worker node?

For performance purpose, yes. But BigDL can live on it if worker runs multiple executors, which may result in performance loss.

> Does BigDL clone model for each executor even if they are multiple executors on same worker node?

Yes. I don't think it's easy to share something between executors. Please correct me if I'm wrong,

>Does Big dl partition input RDD by number of executors even if they are on same worker node? . Example if there are 12 executors distributed in 5 worker nodes, will there be 12 partitions that each executor works on?

Yes.

> Do all cores of an executor work on the same data set partition and aggregate trained model results before broadcasting to BlockManager?

Yes.

> Where does the DistributedOptimizer code run? In the spark-submit job of the client in deployMode = client?

Some of the code run in the driver(where your submit your code if deployMode = client). Some of them run in the worker... **But all computing intensive code(model forward/backward/weight update) runs on workers.**

>While doing these experiments I have encountered following issues:
--netty io issues between executors and driver
--OOM issues
--job failure when only 1 task fails [ no retry on another executor]

For the first, can you provide how to get the io issue so we can look into it. For the second, the VGG model consumes much memory. You can reduce the batch size, and we're working on optimizing the memory usage.  For the third, did you open the model cache option, if so, the training process should retry from last checkpoint.

> Can you provide a best known configuration of spark standalone cluster for bigDL?

For your configuration, say you have 1 master and 4 workers. I suggest that you open 4 executors and each executor use 28 cores. Your server may turn on hyperthreading, so there are 56 v cores. User physical core number instead of vcore number when training model.

**Comment by yiheng** [comment]
By the way, I think email group is a better place for such discussion.
